---
name: Testing

on:
  pull_request:
    branches:
      - main

env:
  POETRY_VERSION: "1.1.14"

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pre-commit-hook:
          - isort
          - black
          - flake8
          - mypy
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/checkout@v2
      - run: |
          python -m pip install poetry==${POETRY_VERSION}
          poetry install
          poetry run pre-commit install-hooks
      - run: poetry run pre-commit run ${{ matrix.pre-commit-hook }} --all-files --show-diff-on-failure
