---
name: tests

on:
  pull_request:
    branches: [ main ]

env:
  POETRY_VERSION: "1.1.14"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SOURCES_DIR: sources
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - run: |
          python -m pip install poetry==${POETRY_VERSION}
          poetry install
      - run: poetry run pytest -vv
